a=int(input("introduce el valor a:  "))
b=int(input("introduce el valor b:  "))
c=int(input("introduce el valor c:  "))
x=(((b*b)-4*(a)*(c))**1/2)
x1=(-b+(x))/(2*a)
print("el valor de x1 es:  ",x1)
print(x1)