x1=int(input("introduce el valor X1:   "))
y1=int(input("introduce el valor Y1:   "))
x2=int(input("introduce el valor  X2:  "))
y2=int(input("introduce el valor  Y2:  "))
d=((x2-x1)**2+(y2-y1)**2)**(1/2)
print(d)